package org.but4reuse.adapters.cppcdt.callhierarchy.doxygen;

/**
 * Doxyfile source for version 1.8.13
 * 
 * // TODO Make a self contained plugin file
 * 
 * @author sandu.postaru
 *
 */

public class DoxygenConfigSource {

	private DoxygenConfigSource() {
	};

	public final static String TEXT =

			"DOXYFILE_ENCODING      = UTF-8\n" + "\n" + "\n" + "PROJECT_NAME           = \"My Project\"\n" + "\n" + "\n"
					+ "PROJECT_NUMBER         =\n" + "\n" + "\n" + "PROJECT_BRIEF          =\n" + "\n" + "\n"
					+ "PROJECT_LOGO           =\n" + "\n" + "\n" + "OUTPUT_DIRECTORY       =\n" + "\n" + "\n"
					+ "CREATE_SUBDIRS         = NO\n" + "\n" + "\n" + "ALLOW_UNICODE_NAMES    = NO\n" + "\n" + "\n"
					+ "OUTPUT_LANGUAGE        = English\n" + "\n" + "\n" + "BRIEF_MEMBER_DESC      = YES\n" + "\n"
					+ "\n" + "REPEAT_BRIEF           = YES\n" + "\n" + "\n"
					+ "ABBREVIATE_BRIEF       = \"The $name class\" \\\n"
					+ "                         \"The $name widget\" \\\n"
					+ "                         \"The $name file\" \\\n" + "                         is \\\n"
					+ "                         provides \\\n" + "                         specifies \\\n"
					+ "                         contains \\\n" + "                         represents \\\n"
					+ "                         a \\\n" + "                         an \\\n"
					+ "                         the\n" + "\n" + "\n" + "ALWAYS_DETAILED_SEC    = NO\n" + "\n" + "\n"
					+ "INLINE_INHERITED_MEMB  = NO\n" + "\n" + "\n" + "FULL_PATH_NAMES        = YES\n" + "\n" + "\n"
					+ "STRIP_FROM_PATH        =\n" + "\n" + "\n" + "STRIP_FROM_INC_PATH    =\n" + "\n" + "\n"
					+ "SHORT_NAMES            = NO\n" + "\n" + "\n" + "JAVADOC_AUTOBRIEF      = NO\n" + "\n" + "\n"
					+ "QT_AUTOBRIEF           = NO\n" + "\n" + "\n" + "MULTILINE_CPP_IS_BRIEF = NO\n" + "\n" + "\n"
					+ "INHERIT_DOCS           = YES\n" + "\n" + "\n" + "SEPARATE_MEMBER_PAGES  = NO\n" + "\n" + "\n"
					+ "TAB_SIZE               = 4\n" + "\n" + "\n" + "ALIASES                =\n" + "\n" + "\n"
					+ "TCL_SUBST              =\n" + "\n" + "\n" + "OPTIMIZE_OUTPUT_FOR_C  = NO\n" + "\n" + "\n"
					+ "OPTIMIZE_OUTPUT_JAVA   = NO\n" + "\n" + "\n" + "OPTIMIZE_FOR_FORTRAN   = NO\n" + "\n" + "\n"
					+ "OPTIMIZE_OUTPUT_VHDL   = NO\n" + "\n" + "\n" + "EXTENSION_MAPPING      =\n" + "\n" + "\n"
					+ "MARKDOWN_SUPPORT       = YES\n" + "\n" + "\n" + "TOC_INCLUDE_HEADINGS   = 0\n" + "\n" + "\n"
					+ "AUTOLINK_SUPPORT       = YES\n" + "\n" + "\n" + "BUILTIN_STL_SUPPORT    = NO\n" + "\n" + "\n"
					+ "CPP_CLI_SUPPORT        = NO\n" + "\n" + "\n" + "SIP_SUPPORT            = NO\n" + "\n" + "\n"
					+ "IDL_PROPERTY_SUPPORT   = YES\n" + "\n" + "\n" + "DISTRIBUTE_GROUP_DOC   = NO\n" + "\n" + "\n"
					+ "GROUP_NESTED_COMPOUNDS = NO\n" + "\n" + "\n" + "SUBGROUPING            = YES\n" + "\n" + "\n"
					+ "INLINE_GROUPED_CLASSES = NO\n" + "\n" + "\n" + "INLINE_SIMPLE_STRUCTS  = NO\n" + "\n" + "\n"
					+ "TYPEDEF_HIDES_STRUCT   = NO\n" + "\n" + "\n" + "LOOKUP_CACHE_SIZE      = 0\n" + "\n" + "\n"
					+ "\n" + "EXTRACT_ALL            = YES\n" + "\n" + "\n" + "EXTRACT_PRIVATE        = YES\n" + "\n"
					+ "\n" + "EXTRACT_PACKAGE        = NO\n" + "\n" + "\n" + "EXTRACT_STATIC         = YES\n" + "\n"
					+ "\n" + "EXTRACT_LOCAL_CLASSES  = YES\n" + "\n" + "\n" + "EXTRACT_LOCAL_METHODS  = NO\n" + "\n"
					+ "\n" + "EXTRACT_ANON_NSPACES   = NO\n" + "\n" + "\n" + "HIDE_UNDOC_MEMBERS     = NO\n" + "\n"
					+ "\n" + "HIDE_UNDOC_CLASSES     = NO\n" + "\n" + "\n" + "HIDE_FRIEND_COMPOUNDS  = NO\n" + "\n"
					+ "\n" + "HIDE_IN_BODY_DOCS      = NO\n" + "\n" + "\n" + "INTERNAL_DOCS          = NO\n" + "\n"
					+ "\n" + "CASE_SENSE_NAMES       = YES\n" + "\n" + "\n" + "HIDE_SCOPE_NAMES       = NO\n" + "\n"
					+ "\n" + "HIDE_COMPOUND_REFERENCE= NO\n" + "\n" + "\n" + "SHOW_INCLUDE_FILES     = NO\n" + "\n"
					+ "\n" + "SHOW_GROUPED_MEMB_INC  = NO\n" + "\n" + "\n" + "FORCE_LOCAL_INCLUDES   = NO\n" + "\n"
					+ "\n" + "INLINE_INFO            = YES\n" + "\n" + "\n" + "SORT_MEMBER_DOCS       = YES\n" + "\n"
					+ "\n" + "SORT_BRIEF_DOCS        = NO\n" + "\n" + "\n" + "SORT_MEMBERS_CTORS_1ST = NO\n" + "\n"
					+ "\n" + "SORT_GROUP_NAMES       = NO\n" + "\n" + "\n" + "SORT_BY_SCOPE_NAME     = NO\n" + "\n"
					+ "\n" + "STRICT_PROTO_MATCHING  = NO\n" + "\n" + "\n" + "GENERATE_TODOLIST      = YES\n" + "\n"
					+ "\n" + "GENERATE_TESTLIST      = YES\n" + "\n" + "\n" + "GENERATE_BUGLIST       = YES\n" + "\n"
					+ "\n" + "GENERATE_DEPRECATEDLIST= YES\n" + "\n" + "\n" + "ENABLED_SECTIONS       =\n" + "\n" + "\n"
					+ "MAX_INITIALIZER_LINES  = 30\n" + "\n" + "\n" + "SHOW_USED_FILES        = YES\n" + "\n" + "\n"
					+ "SHOW_FILES             = YES\n" + "\n" + "\n" + "SHOW_NAMESPACES        = YES\n" + "\n" + "\n"
					+ "FILE_VERSION_FILTER    =\n" + "\n" + "\n" + "LAYOUT_FILE            =\n" + "\n" + "\n"
					+ "CITE_BIB_FILES         =\n" + "\n" + "\n" + "\n" + "QUIET                  = NO\n" + "\n" + "\n"
					+ "WARNINGS               = YES\n" + "\n" + "\n" + "WARN_IF_UNDOCUMENTED   = YES\n" + "\n" + "\n"
					+ "WARN_IF_DOC_ERROR      = YES\n" + "\n" + "\n" + "WARN_NO_PARAMDOC       = NO\n" + "\n" + "\n"
					+ "WARN_AS_ERROR          = NO\n" + "\n" + "\n"
					+ "WARN_FORMAT            = \"$file:$line: $text\"\n" + "\n" + "\n" + "WARN_LOGFILE           =\n"
					+ "\n" + "\n" + "INPUT_ENCODING         = UTF-8\n" + "\n" + "\n"
					+ "FILE_PATTERNS          = *.cpp \\\n" + "                         *.h\n" + "\n" + "\n"
					+ "RECURSIVE              = NO\n" + "\n" + "\n" + "EXCLUDE                =\n" + "\n" + "\n"
					+ "EXCLUDE_SYMLINKS       = NO\n" + "\n" + "\n" + "EXCLUDE_PATTERNS       =\n" + "\n" + "\n"
					+ "EXCLUDE_SYMBOLS        =\n" + "\n" + "\n" + "EXAMPLE_PATH           =\n" + "\n" + "\n"
					+ "EXAMPLE_PATTERNS       = *\n" + "\n" + "\n" + "EXAMPLE_RECURSIVE      = NO\n" + "\n" + "\n"
					+ "IMAGE_PATH             =\n" + "\n" + "\n" + "INPUT_FILTER           =\n" + "\n" + "\n"
					+ "FILTER_PATTERNS        =\n" + "\n" + "\n" + "FILTER_SOURCE_FILES    = NO\n" + "\n" + "\n"
					+ "FILTER_SOURCE_PATTERNS =\n" + "\n" + "\n" + "USE_MDFILE_AS_MAINPAGE =\n" + "\n" + "\n" + "\n"
					+ "SOURCE_BROWSER         = NO\n" + "\n" + "\n" + "INLINE_SOURCES         = NO\n" + "\n" + "\n"
					+ "STRIP_CODE_COMMENTS    = YES\n" + "\n" + "\n" + "REFERENCED_BY_RELATION = NO\n" + "\n" + "\n"
					+ "REFERENCES_RELATION    = NO\n" + "\n" + "\n" + "REFERENCES_LINK_SOURCE = YES\n" + "\n" + "\n"
					+ "SOURCE_TOOLTIPS        = YES\n" + "\n" + "\n" + "USE_HTAGS              = NO\n" + "\n" + "\n"
					+ "VERBATIM_HEADERS       = YES\n" + "\n" + "\n" + "CLANG_ASSISTED_PARSING = NO\n" + "\n" + "\n"
					+ "CLANG_OPTIONS          =\n" + "\n" + "\n" + "\n" + "ALPHABETICAL_INDEX     = YES\n" + "\n" + "\n"
					+ "COLS_IN_ALPHA_INDEX    = 5\n" + "\n" + "\n" + "IGNORE_PREFIX          =\n" + "\n" + "\n" + "\n"
					+ "GENERATE_HTML          = YES\n" + "\n" + "\n" + "HTML_FILE_EXTENSION    = .html\n" + "\n" + "\n"
					+ "HTML_HEADER            =\n" + "\n" + "\n" + "HTML_FOOTER            =\n" + "\n" + "\n"
					+ "HTML_STYLESHEET        =\n" + "\n" + "\n" + "HTML_EXTRA_STYLESHEET  =\n" + "\n" + "\n"
					+ "HTML_EXTRA_FILES       =\n" + "\n" + "\n" + "HTML_COLORSTYLE_HUE    = 220\n" + "\n" + "\n"
					+ "HTML_COLORSTYLE_SAT    = 100\n" + "\n" + "\n" + "HTML_COLORSTYLE_GAMMA  = 80\n" + "\n" + "\n"
					+ "HTML_TIMESTAMP         = NO\n" + "\n" + "\n" + "HTML_DYNAMIC_SECTIONS  = NO\n" + "\n" + "\n"
					+ "HTML_INDEX_NUM_ENTRIES = 100\n" + "\n" + "\n" + "GENERATE_DOCSET        = NO\n" + "\n" + "\n"
					+ "DOCSET_FEEDNAME        = \"Doxygen generated docs\"\n" + "\n" + "\n"
					+ "DOCSET_BUNDLE_ID       = org.doxygen.Project\n" + "\n" + "\n"
					+ "DOCSET_PUBLISHER_ID    = org.doxygen.Publisher\n" + "\n" + "\n"
					+ "DOCSET_PUBLISHER_NAME  = Publisher\n" + "\n" + "\n" + "GENERATE_HTMLHELP      = NO\n" + "\n"
					+ "\n" + "CHM_FILE               =\n" + "\n" + "\n" + "HHC_LOCATION           =\n" + "\n" + "\n"
					+ "GENERATE_CHI           = NO\n" + "\n" + "\n" + "CHM_INDEX_ENCODING     =\n" + "\n" + "\n"
					+ "BINARY_TOC             = NO\n" + "\n" + "\n" + "TOC_EXPAND             = NO\n" + "\n" + "\n"
					+ "GENERATE_QHP           = NO\n" + "\n" + "\n" + "QCH_FILE               =\n" + "\n" + "\n"
					+ "QHP_NAMESPACE          = org.doxygen.Project\n" + "\n" + "\n" + "QHP_VIRTUAL_FOLDER     = doc\n"
					+ "\n" + "\n" + "QHP_CUST_FILTER_NAME   =\n" + "\n" + "\n" + "QHP_CUST_FILTER_ATTRS  =\n" + "\n"
					+ "\n" + "QHP_SECT_FILTER_ATTRS  =\n" + "\n" + "\n" + "QHG_LOCATION           =\n" + "\n" + "\n"
					+ "GENERATE_ECLIPSEHELP   = NO\n" + "\n" + "\n" + "ECLIPSE_DOC_ID         = org.doxygen.Project\n"
					+ "\n" + "\n" + "DISABLE_INDEX          = NO\n" + "\n" + "\n" + "GENERATE_TREEVIEW      = NO\n"
					+ "\n" + "\n" + "ENUM_VALUES_PER_LINE   = 4\n" + "\n" + "\n" + "TREEVIEW_WIDTH         = 250\n"
					+ "\n" + "\n" + "EXT_LINKS_IN_WINDOW    = NO\n" + "\n" + "\n" + "FORMULA_FONTSIZE       = 10\n"
					+ "\n" + "\n" + "FORMULA_TRANSPARENT    = YES\n" + "\n" + "\n" + "USE_MATHJAX            = NO\n"
					+ "\n" + "\n" + "MATHJAX_FORMAT         = HTML-CSS\n" + "\n" + "\n"
					+ "MATHJAX_RELPATH        = http://cdn.mathjax.org/mathjax/latest\n" + "\n" + "\n"
					+ "MATHJAX_EXTENSIONS     =\n" + "\n" + "\n" + "MATHJAX_CODEFILE       =\n" + "\n" + "\n"
					+ "SEARCHENGINE           = YES\n" + "\n" + "\n" + "SERVER_BASED_SEARCH    = NO\n" + "\n" + "\n"
					+ "EXTERNAL_SEARCH        = NO\n" + "\n" + "\n" + "SEARCHENGINE_URL       =\n" + "\n" + "\n"
					+ "SEARCHDATA_FILE        = searchdata.xml\n" + "\n" + "\n" + "EXTERNAL_SEARCH_ID     =\n" + "\n"
					+ "\n" + "EXTRA_SEARCH_MAPPINGS  =\n" + "\n" + "\n" + "\n" + "GENERATE_LATEX         = NO\n" + "\n"
					+ "\n" + "LATEX_OUTPUT           = latex\n" + "\n" + "\n" + "LATEX_CMD_NAME         = latex\n"
					+ "\n" + "\n" + "MAKEINDEX_CMD_NAME     = makeindex\n" + "\n" + "\n"
					+ "COMPACT_LATEX          = NO\n" + "\n" + "\n" + "PAPER_TYPE             = a4\n" + "\n" + "\n"
					+ "EXTRA_PACKAGES         =\n" + "\n" + "\n" + "LATEX_HEADER           =\n" + "\n" + "\n"
					+ "LATEX_FOOTER           =\n" + "\n" + "\n" + "LATEX_EXTRA_STYLESHEET =\n" + "\n" + "\n"
					+ "LATEX_EXTRA_FILES      =\n" + "\n" + "\n" + "PDF_HYPERLINKS         = YES\n" + "\n" + "\n"
					+ "USE_PDFLATEX           = YES\n" + "\n" + "\n" + "LATEX_BATCHMODE        = NO\n" + "\n" + "\n"
					+ "LATEX_HIDE_INDICES     = NO\n" + "\n" + "\n" + "LATEX_SOURCE_CODE      = NO\n" + "\n" + "\n"
					+ "LATEX_BIB_STYLE        = plain\n" + "\n" + "\n" + "LATEX_TIMESTAMP        = NO\n" + "\n" + "\n"
					+ "\n" + "GENERATE_RTF           = NO\n" + "\n" + "\n" + "RTF_OUTPUT             = rtf\n" + "\n"
					+ "\n" + "COMPACT_RTF            = NO\n" + "\n" + "\n" + "RTF_HYPERLINKS         = NO\n" + "\n"
					+ "\n" + "RTF_STYLESHEET_FILE    =\n" + "\n" + "\n" + "RTF_EXTENSIONS_FILE    =\n" + "\n" + "\n"
					+ "RTF_SOURCE_CODE        = NO\n" + "\n" + "\n" + "\n" + "GENERATE_MAN           = NO\n" + "\n"
					+ "\n" + "MAN_OUTPUT             = man\n" + "\n" + "\n" + "MAN_EXTENSION          = .3\n" + "\n"
					+ "\n" + "MAN_SUBDIR             =\n" + "\n" + "\n" + "MAN_LINKS              = NO\n" + "\n" + "\n"
					+ "\n" + "GENERATE_XML           = YES\n" + "\n" + "\n" + "\n" + "\n"
					+ "XML_PROGRAMLISTING     = YES\n" + "\n" + "\n" + "\n" + "GENERATE_DOCBOOK       = NO\n" + "\n"
					+ "\n" + "DOCBOOK_OUTPUT         = docbook\n" + "\n" + "\n" + "DOCBOOK_PROGRAMLISTING = NO\n" + "\n"
					+ "\n" + "\n" + "GENERATE_AUTOGEN_DEF   = NO\n" + "\n" + "\n" + "\n"
					+ "GENERATE_PERLMOD       = NO\n" + "\n" + "\n" + "PERLMOD_LATEX          = NO\n" + "\n" + "\n"
					+ "PERLMOD_PRETTY         = YES\n" + "\n" + "\n" + "PERLMOD_MAKEVAR_PREFIX =\n" + "\n" + "\n" + "\n"
					+ "ENABLE_PREPROCESSING   = YES\n" + "\n" + "\n" + "MACRO_EXPANSION        = NO\n" + "\n" + "\n"
					+ "EXPAND_ONLY_PREDEF     = NO\n" + "\n" + "\n" + "SEARCH_INCLUDES        = YES\n" + "\n" + "\n"
					+ "INCLUDE_PATH           =\n" + "\n" + "\n" + "INCLUDE_FILE_PATTERNS  =\n" + "\n" + "\n"
					+ "PREDEFINED             =\n" + "\n" + "\n" + "EXPAND_AS_DEFINED      =\n" + "\n" + "\n"
					+ "SKIP_FUNCTION_MACROS   = YES\n" + "\n" + "\n" + "\n" + "TAGFILES               =\n" + "\n" + "\n"
					+ "GENERATE_TAGFILE       =\n" + "\n" + "\n" + "ALLEXTERNALS           = NO\n" + "\n" + "\n"
					+ "EXTERNAL_GROUPS        = YES\n" + "\n" + "\n" + "EXTERNAL_PAGES         = YES\n" + "\n" + "\n"
					+ "PERL_PATH              = /usr/bin/perl\n" + "\n" + "\n" + "\n" + "CLASS_DIAGRAMS         = NO\n"
					+ "\n" + "\n" + "MSCGEN_PATH            =\n" + "\n" + "\n" + "DIA_PATH               =\n" + "\n"
					+ "\n" + "HIDE_UNDOC_RELATIONS   = YES\n" + "\n" + "\n" + "HAVE_DOT               = YES\n" + "\n"
					+ "\n" + "DOT_NUM_THREADS        = 0\n" + "\n" + "\n" + "DOT_FONTNAME           = Helvetica\n"
					+ "\n" + "\n" + "DOT_FONTSIZE           = 10\n" + "\n" + "\n" + "DOT_FONTPATH           =\n" + "\n"
					+ "\n" + "CLASS_GRAPH            = NO\n" + "\n" + "\n" + "COLLABORATION_GRAPH    = NO\n" + "\n"
					+ "\n" + "GROUP_GRAPHS           = NO\n" + "\n" + "\n" + "UML_LOOK               = NO\n" + "\n"
					+ "\n" + "UML_LIMIT_NUM_FIELDS   = 10\n" + "\n" + "\n" + "TEMPLATE_RELATIONS     = NO\n" + "\n"
					+ "\n" + "INCLUDE_GRAPH          = NO\n" + "\n" + "\n" + "INCLUDED_BY_GRAPH      = NO\n" + "\n"
					+ "\n" + "CALL_GRAPH             = YES\n" + "\n" + "\n" + "CALLER_GRAPH           = NO\n" + "\n"
					+ "\n" + "GRAPHICAL_HIERARCHY    = NO\n" + "\n" + "\n" + "DIRECTORY_GRAPH        = NO\n" + "\n"
					+ "\n" + "DOT_IMAGE_FORMAT       = png\n" + "\n" + "\n" + "INTERACTIVE_SVG        = NO\n" + "\n"
					+ "\n" + "DOT_PATH               =\n" + "\n" + "\n" + "DOTFILE_DIRS           =\n" + "\n" + "\n"
					+ "MSCFILE_DIRS           =\n" + "\n" + "\n" + "DIAFILE_DIRS           =\n" + "\n" + "\n"
					+ "PLANTUML_JAR_PATH      =\n" + "\n" + "\n" + "PLANTUML_CFG_FILE      =\n" + "\n" + "\n"
					+ "PLANTUML_INCLUDE_PATH  =\n" + "\n" + "\n" + "DOT_GRAPH_MAX_NODES    = 50\n" + "\n" + "\n"
					+ "MAX_DOT_GRAPH_DEPTH    = 0\n" + "\n" + "\n" + "DOT_TRANSPARENT        = NO\n" + "\n" + "\n"
					+ "DOT_MULTI_TARGETS      = NO\n" + "\n" + "\n" + "GENERATE_LEGEND        = NO\n" + "\n" + "\n"
					+ "DOT_CLEANUP            = NO\n" + "\n" + "\n";

}
